"""Gradio PoC UI for LLM‑assisted KiCad schematic generation.

This is a self‑contained demonstration application. It provides a two‑column
interface where the user can describe a circuit in natural language, select a
few options and trigger a (mock) generation workflow. The backend function
`generate_circuit` returns:

* a textual LLM explanation
* a list of PNG image paths (generated on the fly)
* a list of artifact file paths (schematic, netlist, BOM)
* a log string
* a status flag

All files are written under a temporary ``generated`` directory inside the
project root. The implementation avoids any external dependencies apart from
Gradio itself – the only additional import is ``base64`` for decoding an embed‑
ded placeholder PNG.

The UI uses Gradio components matching the specification:
- ``gr.Textbox`` for the circuit request
- ``gr.Accordion`` for advanced settings
- ``gr.Button`` to start generation
- ``gr.Markdown`` for the LLM output
- ``gr.Gallery`` for schematic previews
- ``gr.File`` for artifact download
- ``gr.Accordion`` with a ``gr.Textbox`` for logs
- ``gr.Chatbot`` (optional) could be added later for interactive refinement.

The code is deliberately simple and type‑annotated for clarity.
"""

import os
import base64
import datetime
from pathlib import Path
import shutil
from typing import List, Dict, Generator


import gradio as gr

# ---------------------------------------------------------------------------
# Helper: write a tiny placeholder PNG (red square) to ``path``.
# The image data is a base64‑encoded 1×1 red pixel PNG, scaled up by the UI.
# ---------------------------------------------------------------------------
_RED_SQUARE_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/5+hHgAFgwJ/"
    "Xc8XWQAAAABJRU5ErkJggg=="
)

def _write_placeholder_png(path: Path) -> None:
    """Create a tiny red‑square PNG at *path*.

    Args:
        path: Destination file path. Parent directories are created automatically.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    png_bytes = base64.b64decode(_RED_SQUARE_PNG_B64)
    path.write_bytes(png_bytes)

# ---------------------------------------------------------------------------
# Mock backend – in a real system this would call the LLM and KiCad tools.
def generate_circuit_stream(
    prompt: str,
    model: str,
    complexity: str,
    generate_bom: bool,
    generate_pcb: bool,
) -> "Generator[tuple[str, list[str], list[str], str, str], None, None]":
    """Stream results while the design script runs.

    This function mirrors ``generate_circuit`` but yields intermediate UI updates
    after each polling interval. The UI can consume the generator with
    ``stream=True`` so images/files appear as soon as they are written.

    Args:
        prompt, model, complexity, generate_bom, generate_pcb – same as
        :func:`generate_circuit`.

    Yields:
        A ``tuple`` matching the Gradio output order:
        ``(llm_output, images, files, logs, status)``. ``status`` is ``"running"``
        while the script is active and becomes ``"complete"`` or ``"failed"``
        on termination.
    """
    import subprocess
    import threading
    import time
    # Resolve the target output directory within the UI app folder (so Gradio can serve the files).
    target_dir = Path(__file__).resolve().parent / "generated" / "custom_generated_design"
    target_dir.mkdir(parents=True, exist_ok=True)

    script_path = Path(__file__).resolve().parent.parent / "back_frontend_stability_agent" / "adversarial_electronics.sh"
    cmd = ["bash", str(script_path), "-d", prompt]

    result = {"logs": "", "returncode": None}
    def _run():
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=str(Path(__file__).resolve().parent.parent),
                timeout=360,
            )
            result["logs"] = proc.stdout + ("\n" if proc.stdout and proc.stderr else "") + proc.stderr
            result["returncode"] = proc.returncode
        except subprocess.TimeoutExpired as e:
            stdout = e.stdout.decode(errors="ignore") if isinstance(e.stdout, (bytes, bytearray)) else (e.stdout or "")
            stderr = e.stderr.decode(errors="ignore") if isinstance(e.stderr, (bytes, bytearray)) else (e.stderr or "")
            result["logs"] = stdout + ("\n" if stdout and stderr else "") + stderr + "\n[Timeout after 360\u202fseconds]"
            result["returncode"] = -1
    thread = threading.Thread(target=_run, daemon=True)
    thread.start()

    seen = set()
    images: List[str] = []
    files: List[str] = []
    llm_output = f"**Design request**: {prompt}\n\nDesign generated by ``adversarial_electronics.sh``."
    # Initial empty result
    src_dir = Path(__file__).resolve().parent.parent / "back_frontend_stability_agent" / "generated" / "custom_generated_design"
    # Poll loop: while script runs, collect new files from the script's generated folder and copy them into the UI's target_dir.
    while thread.is_alive():
        if src_dir.is_dir():
            for p in sorted(src_dir.rglob("*")):
                if p.is_file() and str(p) not in seen:
                    seen.add(str(p))
                    # Copy into UI's generated folder
                    dest = target_dir / p.name
                    shutil.copy2(p, dest)
                    if p.suffix.lower() == ".svg":
                        images.append(str(dest))
                    else:
                        files.append(str(dest))
        # Filter out temporary lock files that may appear.
        files = [f for f in files if Path(f).exists() and not Path(f).name.startswith('~')]
        yield (llm_output, list(images), list(files), result["logs"], "running")
        time.sleep(0.5)
    # Final scan after thread ends.
    if src_dir.is_dir():
        for p in sorted(src_dir.rglob("*")):
            if p.is_file() and str(p) not in seen:
                seen.add(str(p))
                dest = target_dir / p.name
                shutil.copy2(p, dest)
                if p.suffix.lower() == ".svg":
                    images.append(str(dest))
                else:
                    files.append(str(dest))
    files = [f for f in files if Path(f).exists() and not Path(f).name.startswith('~')]
    status = "complete" if result["returncode"] == 0 else "failed"
    yield (llm_output, list(images), list(files), result["logs"], status)


# ---------------------------------------------------------------------------
# Gradio UI definition.
# ---------------------------------------------------------------------------
with gr.Blocks(title="KiCad Design Assistant (PoC)") as demo:
    gr.Markdown("# KiCad Design Assistant – Proof of Concept")
    with gr.Row():
        # Left column – inputs & controls
        with gr.Column(scale=1):
            circuit_input = gr.Textbox(
                lines=8,
                label="Circuit Request",
                placeholder="e.g. Design a 5V buck converter from 12V input capable of delivering 2A.",
            )
            # Advanced settings inside an accordion
            with gr.Accordion("Advanced Settings", open=False):
                model_dropdown = gr.Dropdown(
                    choices=["GPT-4", "GPT-4.1", "Local Llama", "Mock Backend"],
                    value="Mock Backend",
                    label="Model",
                )
                complexity_dropdown = gr.Dropdown(
                    choices=["Simple", "Medium", "Complex"],
                    value="Simple",
                    label="Complexity Level",
                )
                generate_bom_checkbox = gr.Checkbox(
                    label="Generate Bill of Materials",
                    value=False,
                )
                generate_pcb_checkbox = gr.Checkbox(
                    label="Generate PCB Placeholder",
                    value=False,
                )
            generate_btn = gr.Button("Generate Schematic", variant="primary")
            status_md = gr.Markdown("_Idle_")
        # Right column – results
        with gr.Column(scale=2):
            llm_output_md = gr.Markdown(label="LLM Design Output")
            gallery = gr.Gallery(label="Schematic Preview", show_label=True, columns=2)
            file_download = gr.File(label="Design Artifacts", file_count="multiple")
            with gr.Accordion("Execution Logs", open=False):
                log_box = gr.Textbox(lines=15, label="Logs")

    # -----------------------------------------------------------------------
    # Callback wiring
    # -----------------------------------------------------------------------
    generate_btn.click(
        fn=generate_circuit_stream,
        inputs=[
            circuit_input,
            model_dropdown,
            complexity_dropdown,
            generate_bom_checkbox,
            generate_pcb_checkbox,
        ],
        outputs=[
            llm_output_md,
            gallery,
            file_download,
            log_box,
            status_md,
        ],
        queue=True,
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    demo.queue().launch(share=True)
